version: '3'

services:
  app-mysql:
    image: mysql:5.7
    container_name: app-mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=root
      - TZ=Asia/Seoul
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin

  app-was:
    build: .
    ports:
      - 8080:8080
    links:
      - app-mysql
    depends_on:
      - app-mysql
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - TZ=Asia/Seoul
    entrypoint:
      - java
      - -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - -jar
      - /app/app-was.jar